apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kube-copilot.fullname" . }}
data:
  OPENAI_API_MODEL: {{ .Values.openai.apiModel | b64enc }}
  OPENAI_API_BASE: {{ .Values.openai.apiBase | b64enc }}
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc }}
  GOOGLE_API_KEY: {{ .Values.google.apiKey | b64enc }}
  GOOGLE_CSE_ID: {{ .Values.google.cseId | b64enc}}
